name: my_memberlink_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  email_otp: ^3.0.2
  lottie: ^2.0.0
  video_player: ^2.3.0  # Make sure to use the latest version available



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-VariableFont_wght.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-VariableFont_wght.ttf
    
